language: "perl"

perl:
  - "5.14"

sudo: required
services:
  - docker
  - mysql

addons:
  apt:
    packages:
    - graphviz

before_install:
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-hive.git
    - sudo cp -p travisci/mysql_listen_on_all_interfaces.cnf /etc/mysql/conf.d/
    - sudo service mysql restart
    - sleep 10
    - mysql -u root -h localhost -e 'GRANT ALL PRIVILEGES ON *.* TO "travis"@"%"'
    - mysql -hlocalhost -utravis -e "SET GLOBAL sql_mode = 'TRADITIONAL'"
    - mysql --version
    - sudo cat /etc/default/docker
    - sudo sed -i 's/127.0.0.1/0.0.0.0/' /etc/default/docker
    - sudo cat /etc/default/docker
    - sudo service docker restart
    - sleep 10
    - env


install:
    - cpanm -v --installdeps --with-recommends --notest --cpanfile ensembl-hive/cpanfile .
    - docker pull ensemblorg/ensembl-hive-docker-swarm
    - cp -a modules travisci/
    - docker build -t ensemblorg/ensembl-hive-docker-swarm-for-travis travisci/
    - docker swarm init
    - cp -p travisci/hive_config.json $HOME/.hive_config.json

script: "./travisci/run_tests.sh"

notifications:
  slack:
    rooms:
      # coregithub
      - secure: gbyGtAHiHBXgTuoX62FhK3r9Z2ol4uDY63ph2Ex2egTSb7GJqnzTL8RW6cCLRzECxlbLD5/327P8qcUsSvRp7xWCVGlsYwuISqUrv/+huPVQYp2zlAgbZla1/omPEdJMigjUTMex6HvRCYS4EWeKOehHYBR8DEsiz2/Fr5AKjZ5mZDCSVuIFGnYnxb5hlnuuaxiqrSsbQ5RqTeBP/HRnAcCcllemtmzjZODEuGindD9sapkcZmxQKdspACrnxu2EzoO2UYWZEofgoYFPBtyT50O9vfKudSRChm9YXfsWL37Zur8iqYUj9vBirjM4JVPJlPPfX+JOj0kdVShcpcn8OraWX8k0J9QQCZ3m3RkHRfV49ZltOw83kc5XC//OPAg6fa8ikceDsal/iPCPrPp4Kfg/k9Nl3wTCVdofDgRCb6OvkXR08QQXPpWpXk0GyF+3ThTYNNG08cxgHw+DLRHiv3iVK1xByEkeq70lj5QgD3LUnVJ8nmpx94PO/goI7JamPb4+0gVU5Iy6jEqUTnt845Ah4FP9q4Lk3cahXJKY5RtzHTxyegju3gx/EjRDGU5/ocznzJOFFzwY33lpt5C8rtAOwcTD29gJRYYJN6aT9lCregSpPJAEtT/zZcPx1mtTu9XupLnSW/Sfm00Gy97i+4ZH/Auy798tQKsE/v39Vxw=
      # ehive-commits
      - secure: rmh/1X/QcHRLU2HsxAvu0yCIjq69xssgSYHRzLgckexqjD7ShKwQyAov+RynfGFc88QxQ/RMMhuxFqZI/gSIj+6Ahgk7ZeAg/Yl7PekgRRo6I/cFDcNnJHiYxGHhUYnYDTSnS15IP2GnAIgLNWSYV+1Gd41Z7hVeq2H5Oa9OF6mrsruAuLdq+PuIEu8f+eHTCD4PeH8zeyI0olS32ujHCnnPsaBdVfXPeKlZdM0F/7LJK+/gDiz0kjV2RWOpiUghQUdJBxkwn40d9dl5DefqS2lys1r4rjOourD8o9EssNPIysKAdMXx/HzADzyewjBsEkiUKL44EGnrboc9nyRTcd3h6PbwnbTTBrmC51k/HziQPxUoiSnBemGFatgPqCN7Yxsq+15dtZ0iHGJXpX7RxDjWEpNHLo8EwMATo9hOP0kxbLv1MV7WfGQjnEhwnsIRfNk7Z/oytKhL5GDnt0OapWXq2QkQyn2QCyVTlAuEg+aJrVwTKMd1tdbBnqp1Sx8Ozl0buxIQ+S/ozTiVlgm7ZgtNSW2eRzMBEDBG4vBMiF144rTfIPNK3/qcInaCwistl1ojgixt/iZYp7ND8yOt7AqA2nqSLVyh5XTSujAnaQBUSfpSk6Yd6QREcESbHWMJP468ECWrBDHnNZtjc13XR0ejrwKeiRs1HN5eUoQy3Bg=
    on_failure: change
